WAIT_BETWEEN_ACCOUNTS = (10, 30)  # in seconds

MAX_TRIES = 2

RPC = 'https://opbnb-mainnet-rpc.bnbchain.org'

<<<<<<< HEAD
THREADS_NUM = 3
=======
THREADS_NUM = 2
>>>>>>> 4b947bd54d0ca2838bcde5b8c910e5ed4469f893

MOBILE_PROXY = False
DISABLE_SSL = False

UPDATE_STORAGE_ACCOUNT_INFO = False

SKIP_FIRST_ACCOUNTS = 0
RANDOM_ORDER = False

LOOP_RUNS = False

AUTO_UPDATE_INVITES = True
AUTO_UPDATE_INVITES_FROM_FIRST_COUNT = (2, 10)

FAKE_TWITTER = True

DO_TASKS = True
CLAIM_DAILY_INSIGHT = True
CLAIM_RANK_INSIGHTS = True

<<<<<<< HEAD
MIN_INSIGHTS_TO_OPEN = 3
=======
MIN_INSIGHTS_TO_OPEN = 10

>>>>>>> 4b947bd54d0ca2838bcde5b8c910e5ed4469f893
CHECKER_UPDATE_STORAGE = False
