WAIT_BETWEEN_ACCOUNTS = (10, 30)  # in seconds

MAX_TRIES = 3

RPC = 'https://opbnb-mainnet-rpc.bnbchain.org'

THREADS_NUM = 3

MOBILE_PROXY = False
DISABLE_SSL = False

SKIP_FIRST_ACCOUNTS = 0

AUTO_UPDATE_INVITES = True
AUTO_UPDATE_INVITES_FROM_FIRST_COUNT = 3

FAKE_TWITTER = True

DO_TASKS = True
CLAIM_DAILY_INSIGHT = True
CLAIM_RANK_INSIGHTS = True

MIN_INSIGHTS_TO_OPEN = 3
